name: GuardianAC
version: '${project.version}'
main: org.guardiananticheat.guardianac.GuardianAC
api-version: '1.18'
authors: [ItzTobiass]
description: A Minecraft Pro AntiCheat

commands:
  galerts:
    description: Toggle Alerts.
    usage: /galerts
    permission: guardianac.alerts
    permission-message: "You don't have permission to use this command."
  greload:
    description: Reload the plugin with config
    usage: /greload
    permission: guardianac.reload
    permission-message: "You don't have permission to use this command."
  ghelp:
    description: Show the help list
    usage: /ghelp
  ginfo:
    description: Shows information about the GuardianAC plugin.
    usage: /ginfo